let questsionsElectronics = [
    {
      "question":"Was ist ein Transistor?",
      "answer_1":"Ein mechanischer Schalter",
      "answer_2":"Ein optisches Anzeigegerät",
      "answer_3":"Ein elektronisches Bauelement zur Verstärkung von Signalen",
      "answer_4":"Ein Energiemessgerät",
      "right_answer":3,
    },
    {
        "question":"Wofür steht die Abkürzung LED?",
        "answer_1":"Light Emitting Diode",
        "answer_2":"Low Energy Display",
        "answer_3":"Linear Electron Device",
        "answer_4":"Liquid Emission Detector",
        "right_answer":1,
      },
      {
        "question":"Welche Einheit wird verwendet, um elektrischen Widerstand zu messen?",
        "answer_1":"Ampere",
        "answer_2":"Coulomb",
        "answer_3":"Volt",
        "answer_4":"Ohm",
        "right_answer":4,
      },
      {
        "question":"Welcher der folgenden Bestandteile ist kein passives elektronisches Bauelement?",
        "answer_1":"Widerstand",
        "answer_2":"Kondensator",
        "answer_3":"Transistor",
        "answer_4":"Spule",
        "right_answer":3,
      },
      {
        "question":"Was beschreibt das Ohmsche Gesetz?",
        "answer_1":"Die Beziehung zwischen Strom, Spannung und Widerstand",
        "answer_2":"Die Richtung des Stromflusses in einem elektrischen Kreis",
        "answer_3":"Die Geschwindigkeit, mit der Elektronen durch einen Leiter fliessen",
        "answer_4":"Die Leistungsaufnahme eines Geräts",
        "right_answer":1,
      },
];

let questsionsBiologie = [
    {
      "question":"Was ist die grundlegende Einheit des Lebens?",
      "answer_1":"Das Organ",
      "answer_2":"Die Zelle",
      "answer_3":"Das Biomolekül",
      "answer_4":" Das Ökosystem",
      "right_answer":2,
    },
    {
        "question":"Welcher Prozess beschreibt die Umwandlung von Sonnenenergie in chemische Energie durch Pflanzen?",
        "answer_1":"Zellatmung",
        "answer_2":"Fermentation",
        "answer_3":"Photosynthese",
        "answer_4":"Hydrolyse",
        "right_answer":3,
      },
      {
        "question":"Welches Organells findet man ausschließlich in Pflanzenzellen?",
        "answer_1":"Ribosomen",
        "answer_2":"Chloroplasten",
        "answer_3":"Mitochondrien",
        "answer_4":"Lysosomen",
        "right_answer":2,
      },
      {
        "question":"Was ist die DNA?",
        "answer_1":"Ein Energiespeichermolekül",
        "answer_2":"Ein Protein",
        "answer_3":"Ein Enzym",
        "answer_4":"Das Erbmaterial in Zellen",
        "right_answer":4,
      },
      {
        "question":"Wofür steht der Begriff Biodiversität?",
        "answer_1":"Die Überlebensrate einer Art",
        "answer_2":"Die Variation von Lebensräumen in einem Ökosystem",
        "answer_3":"Die Vielfalt an Lebensformen in einem bestimmten Gebiet",
        "answer_4":"Die genetische Veränderung innerhalb einer Population",
        "right_answer":3,
      },
];

let questsionsAnimals = [
    {
      "question":"Welches Tier ist für seine acht Arme und seine Intelligenz bekannt?",
      "answer_1":"Seestern",
      "answer_2":"Qualle",
      "answer_3":"Oktopus",
      "answer_4":"Walhai",
      "right_answer":3,
    },
    {
        "question":" Was ist das größte lebende Landtier?",
        "answer_1":"Elefant",
        "answer_2":"Giraffe",
        "answer_3":"Nashorn",
        "answer_4":"Flusspferd",
        "right_answer":1,
      },
      {
        "question":"Welches Tier gilt als das schnellste Landtier der Welt?",
        "answer_1":"Gepard",
        "answer_2":"Falke",
        "answer_3":"Löwe",
        "answer_4":"Thunfisch",
        "right_answer":1,
      },
      {
        "question":"Welches der folgenden Tiere ist ein Nagetier?",
        "answer_1":"Koala",
        "answer_2":"Eichhörnchen",
        "answer_3":"Känguru",
        "answer_4":"Erdmännchen",
        "right_answer":2,
      },
      {
        "question":"Was ist ein einzigartiges Merkmal der Monotremata, zu denen das Schnabeltier gehört?",
        "answer_1":"Sie können fliegen",
        "answer_2":"Sie legen Eier",
        "answer_3":"Sie haben keine Wirbelsäule",
        "answer_4":"Sie leben ausschließlich im Wasser",
        "right_answer":2,
      },
];

let questsionsGeologie = [
    {
      "question":"Welcher Begriff beschreibt die Bewegung der tektonischen Platten?",
      "answer_1":"Isostasie",
      "answer_2":"Konvektion",
      "answer_3":"Plattenkollision",
      "answer_4":"Plattentektonik",
      "right_answer":4,
    },
    {
        "question":"Was ist ein Mineral?",
        "answer_1":"Ein natürlich vorkommender, homogener Feststoff",
        "answer_2":"Ein synthetisch hergestelltes, kristallines Material",
        "answer_3":"Organisches Material fossiler Herkunft",
        "answer_4":"Eine Flüssigkeit, die unter der Erdoberfläche gefunden wird",
        "right_answer":1,
      },
      {
        "question":"Was ist der Mohs'sche Härtegrad?",
        "answer_1":"Ein Mass für die Dichte eines Minerals",
        "answer_2":"Eine Skala zur Messung der Härte von Mineralen",
        "answer_3":"Ein Test zur Bestimmung der Elastizität von Gestein",
        "answer_4":"Eine Methode zur Altersdatierung von Fossilien",
        "right_answer":2,
      },
      {
        "question":"Was ist der Hauptunterschied zwischen Lava und Magma?",
        "answer_1":"Lava ist heißer als Magma",
        "answer_2":"Lava ist Magma, das an die Erdoberfläche gelangt ist",
        "answer_3":"Magma enthält mehr Gase als Lava",
        "answer_4":"Magma findet man nur in Vulkanen, Lava auch in Gebirgen",
        "right_answer":2,
      },
      {
        "question":"Was versteht man unter Erosion?",
        "answer_1":"Die Ansammlung von Sedimenten an einem Ort",
        "answer_2":"Die Ablagerung von Mineralen aus wässrigen Lösungen",
        "answer_3":"Den Prozess des Gesteinsaufschmelzens unter hohem Druck",
        "answer_4":"Die Abtragung von Gesteinsmaterial durch Wasser, Wind oder Eis",
        "right_answer":4,
      },
];